### ISSUE TITLE
Setting inverter DateTime failed: (TypeError('can only concatenate str (not "datetime.datetime") to str')

### ISSUE THREAD

**Issue by LewisHobden** [GivEnergy/giv_tcp#51]
This may well be user error on my end, but I wanted to double check anyway. For whatever reason (the installers maybe?) my inverter has the wrong date/time set and is out by an hour. 

I wanted to have Home Assistant fix this and keep it updated automatically via scripts but I've been unable to. I've tried via both the API and MQTT directly. Here's a sampling of inputs and results:

## via API
```bash
curl -X POST http://homeassistant:6345/setDateTime \
                       -H "Content-Type: application/json" \
                       -d '{"dateTime": "22/07/2024 10:03:44"}'
```

{"result": "Setting inverter DateTime failed: (<class 'TypeError'>, TypeError('can only concatenate str (not \"datetime.datetime\") to str'), <traceback object at 0x7fda5bd85600>)"}

## via MQTT
```yml
service: mqtt.publish
data:
  topic: GivEnergy/control/<serial>/setDateTime
  payload: "{{ now().strftime(\"%d/%m/%Y %H:%M:%S\") }}"
```

Setting inverter DateTime failed: (<class 'TypeError'>, TypeError('can only concatenate str (not "datetime.datetime") to str'), <traceback object at 0x7fda5bd771c0>)

```yml
service: mqtt.publish
data:
  topic: GivEnergy/control/<serial>/setDateTime
  payload: >-
        {
          "dateTime": "{{ now().strftime('%d/%m/%Y %H:%M:%S') }}"
        }
```

Setting inverter DateTime failed: (<class 'ValueError'>, ValueError('time data \'{"dateTime": "22/07/2024 11:31:14"}\' does not match format \'%d/%m/%Y %H:%M:%S\''), <traceback object at 0x7f8f61ad1680>)

I have checked issues and can't see anything raised similarly. I'm happy to open a PR with a fix but my Python is pretty rusty. Any guidance would be greatly appreciated, even pointing me in the direction of how to set the date and time of the inverter properly.

**Comment by alfwro13** [comment]
I've been trying to the very same thing today after that GE date fiasco and I am hitting the same problem:
```
2024-12-31 16:00:47,950 - GE - mqtt        -  [INFO    ] - Requesting Control Action: setDateTime - {'dateTime': '31/12/2024 16:01:07'}
2024-12-31 16:00:48,807 - GE - write       -  [ERROR   ] - Setting inverter DateTime failed: ('TypeError', 'write.py', 1384)
```

using
```
action: mqtt.publish
data:
  topic: GivEnergy/control/<SN>/setDateTime
  payload: "{{ now().strftime('%d/%m/%Y %H:%M:%S') }}"
```
